-- =====================================================================
-- BDIH Maintenance Platform: import data from the original Excel workbooks
-- (Wholistic Maintenance Calendar FY2026-27 + Four-quarter Maintenance Plan)
-- 44 assets · 12 contractors · 18 historical work orders / purchases
-- Run once in Supabase > SQL Editor. Existing records with the same ID are left unchanged.
-- =====================================================================

insert into public.assets (id, data) values
  ('BDIH-M-01', '{"id":"BDIH-M-01","name":"Air Handling Unit (AHU)","disc":"Mechanical","freq":["Housekeeping","Daily","Monthly","Quarterly","Bi-annual","Annual"],"loc":"Energy Centre","crit":5,"health":82,"status":"due","last":"1 Jun 2026","note":"Next service end of July 2026.","spend":0,"contractor":"In-house","strategy":"Proactive, Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-02', '{"id":"BDIH-M-02","name":"Atrium Smoke Extract Fan","disc":"Mechanical","freq":["Monthly","Quarterly","Bi-annual","Annual"],"loc":"Atrium","crit":5,"health":61,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Predictive & Reactive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-03', '{"id":"BDIH-M-03","name":"Axial Fans (New)","disc":"Mechanical","freq":["Housekeeping","Monthly","Quarterly","Bi-annual","Annual"],"loc":"Energy Centre","crit":3,"health":68,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Predictive & Reactive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-04', '{"id":"BDIH-M-04","name":"Chilled & Hot Water Cassette","disc":"Mechanical","freq":["Monthly","Quarterly","Bi-annual","Annual"],"loc":"Bar 1","crit":3,"health":63,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-05', '{"id":"BDIH-M-05","name":"Civil Sump Pump","disc":"Mechanical","freq":["Quarterly","Bi-annual","Annual"],"loc":"Pump House","crit":3,"health":58,"status":"overdue","last":"Jul 2024","note":"Serviced by Mod Control. Intervals influenced by rainfall; visual checks determine need.","spend":5586,"contractor":"Mod Control","strategy":"Preventive & Predictive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-06', '{"id":"BDIH-M-06","name":"Condensate Sump Pump","disc":"Mechanical","freq":["Housekeeping","Quarterly","Bi-annual","Annual"],"loc":"Energy Centre","crit":2,"health":74,"status":"ok","last":"Dec 2025","note":"Maintenance by casual workers. Extended intervals applicable; regular visual inspections.","spend":0,"contractor":"Casual workers","strategy":"Preventive & Predictive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-07', '{"id":"BDIH-M-07","name":"Extract Fans & CO Detector","disc":"Mechanical","freq":["Daily","Monthly","Quarterly","Bi-annual","Annual"],"loc":"Basement Parking","crit":4,"health":60,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Preventive & Predictive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-08', '{"id":"BDIH-M-08","name":"Domestic Hot Water Recirculating Pumps","disc":"Mechanical","freq":["Housekeeping","Bi-annual","Annual"],"loc":"Bar 3","crit":2,"health":66,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Predictive & Reactive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-09', '{"id":"BDIH-M-09","name":"Domestic Booster Pump","disc":"Mechanical","freq":["Housekeeping","Quarterly","Bi-annual"],"loc":"Pump House","crit":4,"health":84,"status":"ok","last":"Nov 2025","note":"Serviced by Climate Control.","spend":25292.04,"contractor":"Climate Control","strategy":"Predictive & Reactive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-10', '{"id":"BDIH-M-10","name":"Direct Expansion (DX) Ceiling Cassette AC Unit","disc":"Mechanical","freq":["Monthly","Quarterly","Bi-annual","Annual"],"loc":"Bar 3","crit":2,"health":64,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-11', '{"id":"BDIH-M-11","name":"Fan Coil Unit (FCU)","disc":"Mechanical","freq":["Monthly","Quarterly","Bi-annual","Annual"],"loc":"Bar 1","crit":3,"health":88,"status":"ok","last":"May 2026","note":"Serviced by Climate Control.","spend":8755.2,"contractor":"Climate Control","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-12', '{"id":"BDIH-M-12","name":"Fire Pumps","disc":"Mechanical","freq":["Housekeeping","Daily","Weekly","Monthly","Bi-annual","Annual"],"loc":"Pump House","crit":5,"health":57,"status":"overdue","last":"No record","note":"Test runs and daily visual inspections conducted in-house.","spend":0,"contractor":"In-house","strategy":"Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-13', '{"id":"BDIH-M-13","name":"Fire Fighting Equipment","disc":"Mechanical","freq":["Housekeeping","Daily","Weekly","Monthly","Bi-annual","Annual"],"loc":"Site-wide","crit":5,"health":65,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-14', '{"id":"BDIH-M-14","name":"Guard House Extract Fans (New)","disc":"Mechanical","freq":["Monthly","Quarterly","Bi-annual","Annual"],"loc":"Guard House","crit":1,"health":70,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-15', '{"id":"BDIH-M-15","name":"Janitor Room Extract Fans (New)","disc":"Mechanical","freq":["Monthly","Quarterly","Bi-annual","Annual"],"loc":"Bar 3","crit":1,"health":71,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-16', '{"id":"BDIH-M-16","name":"Janitor Sump Pump","disc":"Mechanical","freq":["Monthly","Quarterly","Bi-annual","Annual"],"loc":"Bar 1 / Bar 3","crit":3,"health":72,"status":"overdue","last":"Jun 2026","note":"Two Bar 3 pumps replaced by Thembezulu (Jan 2026, P37,900). Two Bar 1 pumps replaced by Mod Control (Jun 2026, P36,936).","spend":74836,"contractor":"Mod Control / Thembezulu","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-17', '{"id":"BDIH-M-17","name":"Lift Pit Sump Pump","disc":"Mechanical","freq":["Quarterly","Bi-annual","Annual"],"loc":"Bar 1","crit":3,"health":62,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-18', '{"id":"BDIH-M-18","name":"Pressurization Pump","disc":"Mechanical","freq":["Monthly","Bi-annual","Annual"],"loc":"Energy Centre","crit":4,"health":64,"status":"overdue","last":"No record","note":"Routine visual inspections carried out in-house.","spend":0,"contractor":"In-house","strategy":"Predictive & Reactive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-19', '{"id":"BDIH-M-19","name":"Primary Pump","disc":"Mechanical","freq":["Housekeeping","Daily","Monthly","Bi-annual","Annual"],"loc":"Energy Centre","crit":5,"health":63,"status":"overdue","last":"No record","note":"Routine visual inspections carried out in-house.","spend":0,"contractor":"In-house","strategy":"Predictive & Reactive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-20', '{"id":"BDIH-M-20","name":"Secondary Pump","disc":"Mechanical","freq":["Housekeeping","Daily","Monthly","Bi-annual","Annual"],"loc":"Energy Centre","crit":5,"health":62,"status":"overdue","last":"No record","note":"Routine visual inspections carried out in-house.","spend":0,"contractor":"In-house","strategy":"Predictive & Reactive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-21', '{"id":"BDIH-M-21","name":"Run Around Coil Pump","disc":"Mechanical","freq":["Housekeeping","Daily","Monthly","Bi-annual","Annual"],"loc":"Bar 1","crit":3,"health":null,"status":"restoration","last":"—","note":"Part of restoration; maintenance scheduled after handover.","spend":0,"contractor":"—","strategy":"Predictive & Reactive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-22', '{"id":"BDIH-M-22","name":"Sololift Toilet Lifting Station Pump","disc":"Mechanical","freq":["Housekeeping","Annual"],"loc":"Bar 3","crit":3,"health":41,"status":"critical","last":"No record","note":"3 of 4 on site require replacement; purchase requisition to be submitted.","spend":0,"contractor":"—","strategy":"Predictive & Reactive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-23', '{"id":"BDIH-M-23","name":"Toilet Extract Fans","disc":"Mechanical","freq":["Monthly","Quarterly","Bi-annual","Annual"],"loc":"Bar 1 / Bar 3","crit":2,"health":67,"status":"overdue","last":"No record","note":"Routine visual inspections carried out in-house.","spend":0,"contractor":"In-house","strategy":"Predictive & Reactive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-24', '{"id":"BDIH-M-24","name":"Transformer Room Extract Fans","disc":"Mechanical","freq":["Monthly","Quarterly","Bi-annual","Annual"],"loc":"Energy Centre","crit":4,"health":66,"status":"overdue","last":"No record","note":"Routine visual inspections carried out in-house.","spend":0,"contractor":"In-house","strategy":"Predictive & Reactive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-25', '{"id":"BDIH-M-25","name":"Gorman Rupp Pumps","disc":"Mechanical","freq":["Housekeeping","Daily","Weekly","Monthly","Bi-annual","Annual"],"loc":"Pump House","crit":5,"health":79,"status":"ok","last":"Jun 2026","note":"Serviced/overhauled by AF Sandilands (Feb 2026, P99,307.68). Control panel upgraded by Miracle Control (Jun 2026, P14,991). Muncher repair by Multiwates ongoing (P7,410).","spend":121708.68,"contractor":"AF Sandilands","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-26', '{"id":"BDIH-M-26","name":"Pump Station Backup Generator","disc":"Mechanical","freq":["Housekeeping","Bi-annual","Annual"],"loc":"Pump House","crit":5,"health":55,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-27', '{"id":"BDIH-M-27","name":"Chillers","disc":"Mechanical","freq":["Housekeeping","Quarterly","Bi-annual","Annual"],"loc":"Energy Centre","crit":5,"health":38,"status":"critical","last":"Jul 2026","note":"PO issued to Intramech for Chiller 2 repair; scheduling in progress. Jun 2025 repair on Chiller 2 and Chiller 3 compressor assessment.","spend":129442.6,"contractor":"Intramech","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-28', '{"id":"BDIH-M-28","name":"Water Treatment System","disc":"Mechanical","freq":["Monthly","Quarterly","Bi-annual","Annual"],"loc":"Energy Centre","crit":4,"health":69,"status":"overdue","last":"Mar 2025","note":"Water testing and chemical dosing by AquaPro Water Treatment.","spend":0,"contractor":"AquaPro","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-29', '{"id":"BDIH-M-29","name":"Condensing Unit Heat Pump","disc":"Mechanical","freq":["Monthly","Quarterly","Bi-annual","Annual"],"loc":"Bar 1","crit":3,"health":76,"status":"ok","last":"Jun 2026","note":"Casual workers Dec 2025. Two Bar 1 pumps replaced by Mod Control Jun 2026.","spend":36936,"contractor":"Mod Control","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-30', '{"id":"BDIH-M-30","name":"Sewage Sump Pump","disc":"Mechanical","freq":["Housekeeping","Quarterly","Annual"],"loc":"Pump House","crit":4,"health":60,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-31', '{"id":"BDIH-M-31","name":"Diesel Bulk Storage Tank","disc":"Mechanical","freq":["Housekeeping","Daily"],"loc":"Energy Centre","crit":4,"health":78,"status":"ok","last":"Daily check","note":"Daily visual checks.","spend":0,"contractor":"In-house","strategy":"Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-32', '{"id":"BDIH-M-32","name":"Cyclone Fans","disc":"Mechanical","freq":["Daily","Monthly","Quarterly","Bi-annual","Annual"],"loc":"Energy Centre","crit":2,"health":59,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Predictive & Reactive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-M-33', '{"id":"BDIH-M-33","name":"Building Management System (BMS)","disc":"Mechanical","freq":["Daily","Monthly","Quarterly","Bi-annual","Annual"],"loc":"Control Room","crit":5,"health":58,"status":"overdue","last":"Aug 2024","note":"Serviced by Atbro Systems.","spend":62791.2,"contractor":"Atbro Systems","strategy":"Predictive & Reactive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-E-01', '{"id":"BDIH-E-01","name":"Ring Main Unit (RMU)","disc":"Electrical","freq":["Housekeeping","Annual"],"loc":"Substation","crit":5,"health":60,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-E-02', '{"id":"BDIH-E-02","name":"Transformer","disc":"Electrical","freq":["Housekeeping","Monthly","Quarterly","Bi-annual","Annual"],"loc":"Substation","crit":5,"health":62,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-E-03', '{"id":"BDIH-E-03","name":"Busbar System","disc":"Electrical","freq":["Monthly","Quarterly","Annual"],"loc":"Energy Centre","crit":4,"health":66,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-E-04', '{"id":"BDIH-E-04","name":"Main Low Voltage (LV) Switchgear","disc":"Electrical","freq":["Housekeeping","Monthly","Quarterly","Annual"],"loc":"Energy Centre","crit":5,"health":64,"status":"overdue","last":"No record","note":"Monthly power-meter reading to be recorded.","spend":0,"contractor":"—","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-E-05', '{"id":"BDIH-E-05","name":"Distribution Boards","disc":"Electrical","freq":["Housekeeping","Monthly","Bi-annual","Annual"],"loc":"Site-wide","crit":4,"health":67,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-E-06', '{"id":"BDIH-E-06","name":"Uninterruptible Power Supply (UPS)","disc":"Electrical","freq":["Housekeeping","Daily","Monthly","Quarterly","Bi-annual","Annual"],"loc":"Control Room","crit":5,"health":61,"status":"overdue","last":"27 Feb 2025","note":"Serviced by Algebraic Engineering.","spend":0,"contractor":"Algebraic Engineering","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-E-07', '{"id":"BDIH-E-07","name":"Lighting","disc":"Electrical","freq":["Daily","Monthly","Quarterly","Annual"],"loc":"Site-wide","crit":4,"health":47,"status":"critical","last":"Dec 2025","note":"Spot checks and bulb replacement by casual workers. Emergency staircase lights require urgent replacement; one quotation (P328,973.59) received from SE.","spend":0,"contractor":"Casual workers","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-E-08', '{"id":"BDIH-E-08","name":"Wiring Devices","disc":"Electrical","freq":["Monthly","Annual"],"loc":"Site-wide","crit":2,"health":70,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-E-09', '{"id":"BDIH-E-09","name":"Fire Detection & Voice Evacuation","disc":"Electrical","freq":["Daily","Weekly","Quarterly","Bi-annual","Annual"],"loc":"Site-wide","crit":5,"health":52,"status":"overdue","last":"Jul 2024","note":"Serviced by Sharps Electrical (P57,285.23). Next service delayed by Bar 1 restoration works.","spend":57285.23,"contractor":"Sharps Electrical","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-E-10', '{"id":"BDIH-E-10","name":"Earthing & Lightning Protection","disc":"Electrical","freq":["Annual"],"loc":"Site-wide","crit":4,"health":65,"status":"overdue","last":"No record","note":"No previous maintenance records available.","spend":0,"contractor":"—","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb),
  ('BDIH-E-11', '{"id":"BDIH-E-11","name":"Automatic Standby Diesel Generator","disc":"Electrical","freq":["Housekeeping","Daily","Bi-annual","Annual"],"loc":"Energy Centre","crit":5,"health":56,"status":"overdue","last":"4 May 2026","note":"No previous maintenance records; batteries replaced 04 May 2026. Service-hour intervals 250–12,000 h.","spend":0,"contractor":"In-house","strategy":"Predictive & Preventive","retired":false,"retiredAt":"","retiredReason":"","installed":"","warranty":"","evidence":[]}'::jsonb)
on conflict (id) do nothing;

insert into public.contractors (id, data) values
  ('c1', '{"id":"c1","name":"Intramech","scope":"HVAC · chillers","notes":"Via PWS","contact":"","email":"","phone":"","active":true}'::jsonb),
  ('c2', '{"id":"c2","name":"AF Sandilands","scope":"Pumps","notes":"","contact":"","email":"","phone":"","active":true}'::jsonb),
  ('c3', '{"id":"c3","name":"Mod Control","scope":"Pumps · controls","notes":"","contact":"","email":"","phone":"","active":true}'::jsonb),
  ('c4', '{"id":"c4","name":"Atbro Systems","scope":"BMS","notes":"","contact":"","email":"","phone":"","active":true}'::jsonb),
  ('c5', '{"id":"c5","name":"Sharps Electrical","scope":"Fire detection","notes":"","contact":"","email":"","phone":"","active":true}'::jsonb),
  ('c6', '{"id":"c6","name":"Thembezulu (Pty) Ltd","scope":"Pumps","notes":"","contact":"","email":"","phone":"","active":true}'::jsonb),
  ('c7', '{"id":"c7","name":"Climate Control","scope":"HVAC","notes":"","contact":"","email":"","phone":"","active":true}'::jsonb),
  ('c8', '{"id":"c8","name":"Miracle Control","scope":"Control panels","notes":"","contact":"","email":"","phone":"","active":true}'::jsonb),
  ('c9', '{"id":"c9","name":"Multiwates","scope":"Wastewater","notes":"","contact":"","email":"","phone":"","active":true}'::jsonb),
  ('c10', '{"id":"c10","name":"AquaPro Water Treatment","scope":"Water treatment","notes":"","contact":"","email":"","phone":"","active":true}'::jsonb),
  ('c11', '{"id":"c11","name":"Algebraic Engineering","scope":"UPS","notes":"","contact":"","email":"","phone":"","active":true}'::jsonb),
  ('c12', '{"id":"c12","name":"SE","scope":"Electrical · lighting","notes":"","contact":"","email":"","phone":"","active":true}'::jsonb)
on conflict (id) do nothing;

insert into public.work_orders (id, data) values
  ('WO-2401', '{"id":"WO-2401","asset":"BDIH-M-05","title":"Civil sump pump service","type":"Preventive","contractor":"Mod Control","awardDate":"2024-07-15","serviceDate":"2024-07-15","amount":5586,"procurement":"Paid","status":"Closed","priority":"Routine","po":"PO-2024-310","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2024-07-15T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2402', '{"id":"WO-2402","asset":"BDIH-M-33","title":"BMS service","type":"Preventive","contractor":"Atbro Systems","awardDate":"2024-08-15","serviceDate":"2024-08-15","amount":62791.2,"procurement":"Paid","status":"Closed","priority":"Routine","po":"PO-2024-311","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2024-08-15T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2403', '{"id":"WO-2403","asset":"BDIH-E-09","title":"Fire detection & voice evacuation service","type":"Preventive","contractor":"Sharps Electrical","awardDate":"2024-07-20","serviceDate":"2024-07-20","amount":57285.23,"procurement":"Paid","status":"Closed","priority":"Routine","po":"PO-2024-312","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2024-07-20T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2404', '{"id":"WO-2404","asset":"BDIH-M-27","title":"Chiller call-out: flow switches replaced (R)","type":"Corrective","contractor":"Intramech","awardDate":"2024-02-15","serviceDate":"2024-02-15","amount":33377.25,"procurement":"Paid","status":"Closed","priority":"High","po":"PO-2024-313","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2024-02-15T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2405', '{"id":"WO-2405","asset":"BDIH-E-06","title":"UPS service","type":"Preventive","contractor":"Algebraic Engineering","awardDate":"2025-02-27","serviceDate":"2025-02-27","amount":0,"procurement":"Paid","status":"Closed","priority":"Routine","po":"","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2025-02-27T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2406', '{"id":"WO-2406","asset":"BDIH-M-28","title":"Water testing & chemical dosing","type":"Preventive","contractor":"AquaPro Water Treatment","awardDate":"2025-03-15","serviceDate":"2025-03-15","amount":0,"procurement":"Paid","status":"Closed","priority":"Routine","po":"","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2025-03-15T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2407', '{"id":"WO-2407","asset":"BDIH-M-27","title":"Chiller 2 repair; Chiller 3 compressor rigging (R)","type":"Corrective","contractor":"Intramech","awardDate":"2025-06-15","serviceDate":"2025-06-15","amount":129442.6,"procurement":"Paid","status":"Closed","priority":"High","po":"PO-2025-316","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2025-06-15T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2408', '{"id":"WO-2408","asset":"BDIH-M-09","title":"Domestic booster pump service","type":"Preventive","contractor":"Climate Control","awardDate":"2025-11-15","serviceDate":"2025-11-15","amount":25292.04,"procurement":"Paid","status":"Closed","priority":"Routine","po":"PO-2025-317","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2025-11-15T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2409', '{"id":"WO-2409","asset":"BDIH-M-16","title":"Janitor sump: two Bar 3 pumps replaced","type":"Corrective","contractor":"Thembezulu (Pty) Ltd","awardDate":"2026-01-20","serviceDate":"2026-01-20","amount":37900,"procurement":"Paid","status":"Closed","priority":"High","po":"PO-2026-318","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2026-01-20T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2410', '{"id":"WO-2410","asset":"BDIH-M-25","title":"Gorman Rupp pumps service & overhaul","type":"Preventive","contractor":"AF Sandilands","awardDate":"2026-02-15","serviceDate":"2026-02-15","amount":99307.68,"procurement":"Paid","status":"Closed","priority":"Routine","po":"PO-2026-319","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2026-02-15T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2411', '{"id":"WO-2411","asset":"BDIH-M-11","title":"Fan coil unit service","type":"Preventive","contractor":"Climate Control","awardDate":"2026-05-15","serviceDate":"2026-05-15","amount":8755.2,"procurement":"Paid","status":"Closed","priority":"Routine","po":"PO-2026-320","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2026-05-15T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2412', '{"id":"WO-2412","asset":"BDIH-E-11","title":"Generator batteries replaced","type":"Corrective","contractor":"In-house","awardDate":"2026-05-04","serviceDate":"2026-05-04","amount":0,"procurement":"Not required","status":"Closed","priority":"High","po":"","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2026-05-04T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2413', '{"id":"WO-2413","asset":"BDIH-M-16","title":"Janitor sump: two Bar 1 pumps replaced","type":"Corrective","contractor":"Mod Control","awardDate":"2026-06-15","serviceDate":"2026-06-15","amount":36936,"procurement":"Paid","status":"Closed","priority":"High","po":"PO-2026-322","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2026-06-15T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2414', '{"id":"WO-2414","asset":"BDIH-M-25","title":"Gorman Rupp control panel repair & upgrade","type":"Corrective","contractor":"Miracle Control","awardDate":"2026-06-20","serviceDate":"2026-06-20","amount":14991,"procurement":"Invoiced","status":"Completed","priority":"High","po":"PO-2026-323","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2026-06-20T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2415', '{"id":"WO-2415","asset":"BDIH-M-25","title":"Muncher repair and servicing","type":"Corrective","contractor":"Multiwates","awardDate":"2026-06-25","serviceDate":"","amount":7410,"procurement":"PO issued","status":"In progress","priority":"High","po":"PO-2026-324","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2026-06-25T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2416', '{"id":"WO-2416","asset":"BDIH-M-27","title":"Chiller 2 repair works","type":"Corrective","contractor":"Intramech","awardDate":"2026-07-10","serviceDate":"","amount":0,"procurement":"PO issued","status":"Scheduled","priority":"High","po":"","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2026-07-10T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2417', '{"id":"WO-2417","asset":"BDIH-E-07","title":"Emergency staircase lights replacement","type":"Emergency","contractor":"SE","awardDate":"2026-08-20","serviceDate":"","amount":328973.59,"procurement":"Quotations (1 of 3)","status":"On hold","priority":"Critical","po":"","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2026-08-20T08:00","evidence":[],"updates":[],"request":""}'::jsonb),
  ('WO-2418', '{"id":"WO-2418","asset":"BDIH-M-22","title":"Sololift units replacement (3 of 4)","type":"Corrective","contractor":"","awardDate":"2026-09-01","serviceDate":"","amount":0,"procurement":"Requisition pending","status":"Open","priority":"High","po":"","desc":"","raisedBy":"Imported from Excel history sheet","raisedAt":"2026-09-01T08:00","evidence":[],"updates":[],"request":""}'::jsonb)
on conflict (id) do nothing;

insert into public.audit_log (id, data) values ('A-' || gen_random_uuid(), jsonb_build_object('at', to_char(now() at time zone 'Africa/Gaborone','YYYY-MM-DD"T"HH24:MI'), 'by', 'Database administrator (SQL)', 'role', 'System Administrator', 'action', 'Imported', 'ref', 'Excel workbooks', 'detail', '44 assets, 12 contractors, 18 historical orders'));

select (select count(*) from public.assets) as assets, (select count(*) from public.contractors) as contractors, (select count(*) from public.work_orders) as work_orders;
